# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Aplus' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Aplus

  pod 'FSCalendar'
  pod 'SVProgressHUD', :git => 'https://github.com/SVProgressHUD/SVProgressHUD.git'
  pod 'SideMenu'


end
